DVS_Analysis/execute_functions/urls.py
from django.urls import path, include
from . import views


app_name = 'execute_functions'

urlpatterns = [
    path('', views.execute, name='execute'),
    path('draw/', views.draw, name='draw')
]

DVS_Analysis/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('execute_functions.urls', namespace='execute_functions'))
]

execute_functions/urls.py
from django.urls import path
from . import views


app_name = 'execute_functions'

urlpatterns = [
    path('', views.execute, name='execute'),
]

execute_functions/models.py
from django.db import models

# Create your models here.

execute_functions/views.py
import json
import os

from django.http import HttpResponse
from django.shortcuts import render
# from notebooks import DVS_ANALYSIS_FUNCTIONAL, wind_rose
from nbimporter import NotebookLoader


def import_nb(notebook):
    global i
    import nbimporter  # This library is the root and most imp part of importing notebook
    nbimporter.options['only_defs'] = True  # This tells notebook to import every cell and not just methods.

    loader = NotebookLoader()
    name = notebook
    i = loader.load_module(os.path.join('notebooks', name))


def execute(request):
    import_nb("DVS_ANALYSIS_FUNCTIONAL")
    if request.method == 'POST':
        plot_kind = request.POST.get('plot_kind')
        bar_box = i.bar_box(plot_kind) if plot_kind else i.bar_box()
        scatter_plot_limit = request.POST.get('scatter_plot_limit')
        bubble_size = request.POST.get('bubble_size')
        if scatter_plot_limit and bubble_size:
            scatter = i.drawScatter(int(scatter_plot_limit), float(bubble_size))
        elif scatter_plot_limit:
            scatter = i.drawScatter(SCATTER_PLOT_LIMIT=int(scatter_plot_limit))
        elif bubble_size:
            scatter = i.drawScatter(BUBBLE_SIZE=float(bubble_size))
        else:
            scatter = i.drawScatter()

        rand_state = request.POST.get('rand_state')
        cube = i.cube_helix(int(rand_state)) if rand_state else i.cube_helix()
    else:
        bar_box = i.bar_box()
        scatter = i.drawScatter()
        cube = i.cube_helix()
    context = {
        'bar_box': bar_box[2:-1],
        'scatter': scatter[2:-1],
        'cube': cube[2:-1]
    }
    return render(request, 'execute_functions/home.html', context)

templates/execute_functions/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Home</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
     <script src="https://requirejs.org/docs/release/2.3.5/minified/require.js"></script>
</head>
<body style="padding: 5%;">
{% block content %}{% endblock %}

</body>
</html>

templates/execute_functions/home.html
{% extends 'execute_functions/base.html' %}
{% block content %}
    <form method="post" action="{% url 'execute_functions:execute' %}">
        {% csrf_token %}
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="row">
                        {% if bar_box %}
                            <img src="data:image/png;base64, {{ bar_box }}" alt="Red dot" style="max-width: 100%; height: 250px;" />
                        {% endif %}
                    </div>
                    <div class="row">
                        <div class="col">
                            <input type="text" class="form-control" placeholder="plot kind" name="plot_kind">
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="row">
                        {% if scatter %}
                            <img src="data:image/png;base64, {{ scatter }}" alt="Red dot" style="max-width: 100%; height: 250px;" />
                        {% endif %}
                    </div>
                    <div class="row">

                        <div class="col">
                            <input type="text" class="form-control" placeholder="scatter limit" name="scatter_plot_limit">
                        </div>
                        <div class="col">
                            <input type="text" class="form-control" placeholder="bubble size" name="bubble_size">
                        </div>

                    </div>
                </div>
                <div class="col">
                    <div class="row">
                        {% if cube %}
                            <img src="data:image/png;base64, {{ cube }}" alt="Red dot" style="max-width: 100%; height: 250px;"/>
                        {% endif %}
                    </div>
                    <div class="row">
                        <div class="col">
                            <input type="text" class="form-control" placeholder="random state" name="rand_state">
                        </div>
                    </div>
                </div>
            </div>
            <div class="row justify-content-md-center mt-5">
                <div class="col-3">
                    <button type="submit" class="btn btn-primary bt-block">Generate graphs</button>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div id="graph"></div>
                </div>
            </div>
        </div>

    </form>
{% endblock %}